apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mean-okteto-sample.fullname" . }}-api
  labels:
    {{- include "mean-okteto-sample.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mean-okteto-sample.name" . }}-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mean-okteto-sample.name" . }}-api
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: okteto/mean-okteto-sample-api
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/articles
              port: 3000
          readinessProbe:
            httpGet:
              path: /api/articles
              port: 3000
          resources:
            limits:
              cpu: 1
