apiVersion: v1
kind: Service
metadata:
  name: {{ include "mean-okteto-sample.fullname" . }}-frontend
  labels:
    {{- include "mean-okteto-sample.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mean-okteto-sample.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
